### ISSUE TITLE
about “data_sample”

### ISSUE THREAD

**Issue by Didudia** [magentech/magetheme#1]
I got a problem about data_sample:
I'm installed SM magetheme successfully,but the home page is not normally displayed, i thought is about "data_sample" folder,because i didn't upload it.
I want to know upload to where.thanks!

**Comment by magentech** [comment]
> I got a problem about data_sample:
> I'm installed SM magetheme successfully,but the home page is not normally displayed, i thought is about "data_sample" folder,because i didn't upload it.
> I want to know upload to where.thanks!

hi: Didudia ,
Please import sample_data.sql before installing. Or you can use the import demo feature: https://i.imgur.com/UFqMZxq.png
or submit ticket here: https://www.magentech.com/support/tickets

Thanks!

**Comment by Didudia** [comment]
how to import sample_data.sql?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magentech/free-magento2-theme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 上午9:59
收件人:&nbsp;"magentech/free-magento2-theme"<free-magento2-theme@noreply.github.com&gt;;
抄送:&nbsp;"憨憨、"<1064878181@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [magentech/free-magento2-theme] about “data_sample” (#1)





  
I got a problem about data_sample:
 I'm installed SM magetheme successfully,but the home page is not normally displayed, i thought is about "data_sample" folder,because i didn't upload it.
 I want to know upload to where.thanks!
  
hi: Didudia ,
 Please import sample_data.sql before installing. Or you can use the import demo feature: https://i.imgur.com/UFqMZxq.png
 or submit ticket here: https://www.magentech.com/support/tickets
 
Thanks!

**Comment by magentech** [comment]
> how to import sample_data.sql?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "magentech/free-magento2-theme" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月7日(星期一) 上午9:59 收件人:&nbsp;"magentech/free-magento2-theme"<free-magento2-theme@noreply.github.com&gt;; 抄送:&nbsp;"憨憨、"<1064878181@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [magentech/free-magento2-theme] about “data_sample” (#1) I got a problem about data_sample: I'm installed SM magetheme successfully,but the home page is not normally displayed, i thought is about "data_sample" folder,because i didn't upload it. I want to know upload to where.thanks! hi: Didudia , Please import sample_data.sql before installing. Or you can use the import demo feature: https://i.imgur.com/UFqMZxq.png or submit ticket here: https://www.magentech.com/support/tickets Thanks! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hi, please view detail in user guide: http://documentation.flytheme.net/sm-magetheme/#quickstart
Thanks!

**Comment by Didudia** [comment]
it only show me how to use"app"and"pub" folder,no guide for "sample_data" folder.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Magentech"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 上午10:13
收件人: "magentech/free-magento2-theme"<free-magento2-theme@noreply.github.com&gt;; 
抄送: "憨憨、"<1064878181@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [magentech/free-magento2-theme] about “data_sample” (#1)





  
how to import sample_data.sql?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "magentech/free-magento2-theme" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月7日(星期一) 上午9:59 收件人:&nbsp;"magentech/free-magento2-theme"<free-magento2-theme@noreply.github.com&gt;; 抄送:&nbsp;"憨憨、"<1064878181@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [magentech/free-magento2-theme] about “data_sample” (#1) I got a problem about data_sample: I'm installed SM magetheme successfully,but the home page is not normally displayed, i thought is about "data_sample" folder,because i didn't upload it. I want to know upload to where.thanks! hi: Didudia , Please import sample_data.sql before installing. Or you can use the import demo feature: https://i.imgur.com/UFqMZxq.png or submit ticket here: https://www.magentech.com/support/tickets Thanks! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
hi, please view detail in user guild: http://documentation.flytheme.net/sm-magetheme/#quickstart
 Thanks!

**Comment by magentech** [comment]
**sample_data** folder is **data_quickstart** folder in user guilde. Please view detail in user guide.
Thanks!
